name: Build & Deploy to AWS EC2 using Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

        env:
          MONGO_URI: ${{ secrets.DB_URI }}
          PORT: ${{ secrets.PORT }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sagar246/spyne-ai:latest

      - name: Verify the pushed docker image
        run: docker pull sagar246/spyne-ai:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/spyne-ai  # Ensure directory exists
            cd /home/ubuntu/spyne-ai
            ls -la  # Debugging step to verify files
            if [ -f "docker-compose.yml" ]; then
              sudo docker-compose down
              sudo docker-compose pull
              sudo docker-compose up -d
            else
              echo "Error: docker-compose.yml not found!"
              exit 1
            fi
